name: ADAtickets-dev

services:
  adatickets.pgweb:
    container_name: Pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8082:8081" 
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRESUSER:?error}:${POSTGRESPASSWORD:?error}@adatickets.postgresql:5432/adatickets?sslmode=disable
    depends_on:
      adatickets.postgresql:
        condition: service_healthy
    networks:
      - network

  adatickets.apiservice:
    build:
      context: .
      args:
       - BUILD_CONFIGURATION=Debug
      dockerfile: ADAtickets.ApiService/Dockerfile
      tags:
        - andrexace/adatickets-api:dev
    image: andrexace/adatickets-api:dev
    environment:
      # ASP.NET configuration variables
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTPASSWORD:?error}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTPATH:-/https/aspnetapp.pfx}
      # Database connection string
      - ConnectionStrings__PostgreSQL=Host=localhost;Port=5432;Database=adatickets;Username=${POSTGRESUSER:?error};Password=${POSTGRESPASSWORD:?error}
      # Entra configuration variables
      - Entra__Authority=https://login.microsoftonline.com/${TENANTID:?error}/v2.0/
      - Entra__Audience=api://${APIAPPID:?error}
      - ExternalEntra__Authority=https://${EXTERNALTENANTNAME:?error}.ciamlogin.com/${EXTERNALTENANTID?:error}/v2.0/ 
      - ExternalEntra__Audience=api://${EXTERNALAPIAPPID:?error}
    volumes:
      - ${VOLUMEPATH:-~/.aspnet/https}:/https:ro
  
  adatickets.web:
    build:
      context: .
      args:
       - BUILD_CONFIGURATION=Debug
      dockerfile: ADAtickets.Web/Dockerfile
      tags:
        - andrexace/adatickets-web:dev
    image: andrexace/adatickets-web:dev
    environment:
      # ASP.NET configuration variables
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTPASSWORD:?error}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTPATH:-/https/aspnetapp.pfx}
      # Entra configuration variables
      - Entra__Authority=https://login.microsoftonline.com/${TENANTID:?error}/v2.0/
      - Entra__Audience=api://${APIAPPID:?error}
      - Entra__CallbackPath=/signin-oidc-entra
      - Entra__Instance=https://login.microsoftonline.com
      - Entra__ResponseType=code
      - Entra__ClientId=${CLIENTAPPID:?error}
      - Entra__Domain=${TENANTNAME:?error}.onmicrosoft.com
      - Entra__TenantId=${TENANTID:?error}
      - Entra__Certificate__DiskPath=${CERTIFICATEDISKPATH:?error}
      - Entra__Certificate__Password=${CERTIFICATEPASSWORD:?error}
      - Entra__DownstreamApi__BaseUrl=https://localhost:7214
      - Entra__DownstreamApi__Scopes__0=api://${APIAPPID:?error}/Read
      - Entra__DownstreamApi__Scopes__1=api://${APIAPPID:?error}/ReadWrite
      - ExternalEntra__Authority=https://${EXTERNALTENANTNAME?:error}.ciamlogin.com/${EXTERNALTENANTID?:error}/v2.0/ 
      - ExternalEntra__Audience=api://${EXTERNALAPIAPPID:?error}
      - ExternalEntra__CallbackPath=/signin-oidc-entra-external
      - ExternalEntra__Instance=https://${EXTERNALTENANTNAME?:error}.ciamlogin.com
      - ExternalEntra__ClientId=${EXTERNALCLIENTAPPID}
      - ExternalEntra__Domain=${EXTERNALTENANTNAME:?error}.onmicrosoft.com
      - ExternalEntra__TenantId=${EXTERNALTENANTID:?error}
      - ExternalEntra__DownstreamApi__Scopes__0=api://${EXTERNALAPIAPPID:?error}/Read
      - ExternalEntra__DownstreamApi__Scopes__1=api://${EXTERNALAPIAPPID:?error}/ReadWrite
    volumes:
      - ${VOLUMEPATH:-~/.aspnet/https}:/https:ro