services:
  adatickets.postgresql:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=ADAtickets
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - adatickets-database-data:/var/lib/postgresql/data
    networks:
      - adatickets-network

  adatickets.apiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
    ports:
      - "5194:8080"
      - "7214:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - adatickets-network

  adatickets.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
    ports:
      - "5207:8080"
      - "7013:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - adatickets-network

networks:
  adatickets-network:
    driver: bridge

volumes:
  adatickets-database-data:
    driver: local
