name: Dev-ADAtickets

services:
  adatickets.apiservice:
    image: adatickets-api
    build:
      context: .
      dockerfile: ADAtickets.ApiService/Dockerfile
    environment:
      # ASP.NET configuration variables
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # Database connection string
      - ConnectionStrings__PostgreSQL=Host=adatickets.postgresql;Port=5432;Database=adatickets;Username=${POSTGRESUSER:?error};Password=${POSTGRESPASSWORD:?error}
      - ConnectionStrings__Redis=adatickets.redis:6379
      # Entra configuration variables
      - Entra__Instance=https://login.microsoftonline.com
      - Entra__TenantId=${TENANTID:?error}
      - Entra__ClientId=${APIAPPID:?error}
      # External Entra configuration variables
      - ExternalEntra__Instance=https://${EXTERNALTENANTID:?error}.ciamlogin.com
      - ExternalEntra__TenantId=${EXTERNALTENANTID:?error}
      - ExternalEntra__ClientId=${EXTERNALAPIAPPID:?error}
      # Azure DevOps configuration variables
      - AzureDevOps__Instance=https://login.microsoftonline.com
      - AzureDevOps__TenantId=${TENANTID:?error}
      - AzureDevOps__ClientId=${APIAPPID:?error}
      - AzureDevOps__ClientCertificates__0__SourceType=Path
      - AzureDevOps__ClientCertificates__0__CertificateDiskPath=/certs/${APIAUTHCERTIFICATENAME:?error}
      - AzureDevOps__ClientCertificates__0__CertificatePassword=${APIAUTHCERTIFICATEPASSWORD:?error}
      # DevOps API configuration variables
      - AzureDevOpsAPI__BaseUrl=https://dev.azure.com/${DEVOPSORGANIZATIONNAME:?error}
      - AzureDevOpsAPI__Scopes__0=499b84ac-1321-427f-aa17-267ca6975798/.default
      # Webhooks configuration variables
      - Webhook__ServicePrincipalIdentifier=${SERVICEPRINCIPALID:?error}
      - Webhook__BasicAuth__Username=${BASICAUTHUSERNAME:?error}
      - Webhook__BasicAuth__Password=${BASICAUTHPASSWORD:?error}
    volumes:
      - ${APIAUTHCERTIFICATEDISKPATH:?error}:/certs:ro

  adatickets.web:
    image: adatickets-web
    build:
      context: .
      dockerfile: ADAtickets.Web/Dockerfile
    environment:
      # ASP.NET configuration variables
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      # Redis connection string
      - ConnectionStrings__Redis=adatickets.redis:6379
      # Entra configuration variables
      - Entra__Instance=https://login.microsoftonline.com
      - Entra__TenantId=${TENANTID:?error}
      - Entra__ClientId=${WEBAPPID:?error}
      - Entra__SkipUnrecognizedRequests=true
      - Entra__CallbackPath=/signin-oidc-entra
      - Entra__SignedOutCallbackPath=/signout-oidc-entra
      - Entra__ClientCertificates__0__SourceType=Path
      - Entra__ClientCertificates__0__CertificateDiskPath=/certs/${WEBAUTHCERTIFICATENAME:?error}
      - Entra__ClientCertificates__0__CertificatePassword=${WEBAUTHCERTIFICATEPASSWORD:?error}
      # External Entra configuration variables
      - ExternalEntra__Instance=https://${EXTERNALTENANTID:?error}.ciamlogin.com
      - ExternalEntra__TenantId=${EXTERNALTENANTID:?error}
      - ExternalEntra__ClientId=${EXTERNALWEBAPPID:?error}
      - ExternalEntra__SkipUnrecognizedRequests=true
      - ExternalEntra__CallbackPath=/signin-oidc-external-entra
      - ExternalEntra__SignedOutCallbackPath=/signout-oidc-external-entra
      - ExternalEntra__ClientCertificates__0__SourceType=Path
      - ExternalEntra__ClientCertificates__0__CertificateDiskPath=/certs/${WEBAUTHCERTIFICATENAME:?error}
      - ExternalEntra__ClientCertificates__0__CertificatePassword=${WEBAUTHCERTIFICATEPASSWORD:?error}
      # ADAtickets API configuration variables
      - ADAticketsAPI__BaseUrl=http://adatickets.apiservice:8080
      - ADAticketsAPI__Scopes__0=api://${APIAPPID:?error}/Read
      - ADAticketsAPI__Scopes__1=api://${APIAPPID:?error}/Write
      # External ADAtickets API configuration variables
      - ExternalADAticketsAPI__BaseUrl=http://adatickets.apiservice:8080
      - ExternalADAticketsAPI__Scopes__0=api://${EXTERNALAPIAPPID:?error}/Read
      - ExternalADAticketsAPI__Scopes__1=api://${EXTERNALAPIAPPID:?error}/Write
    volumes:
      - ${WEBAUTHCERTIFICATEDISKPATH:?error}:/certs:ro
