// <auto-generated />
using System;
using ADAtickets.ApiService.Configs;
using ADAtickets.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ADAtickets.ApiService.Migrations
{
    [DbContext(typeof(ADAticketsDbContext))]
    [Migration("20250817142032_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "priority", new[] { "high", "low", "medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "closed", "unassigned", "waiting_operator", "waiting_user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_type", new[] { "bug", "feature" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_type", new[] { "admin", "operator", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ADAtickets.Shared.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("path");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_attachments_ticket_id");

                    b.HasIndex("Path", "TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_path_ticket_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Edit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EditDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edit_date_time");

                    b.Property<Status>("NewStatus")
                        .HasColumnType("status")
                        .HasColumnName("new_status");

                    b.Property<Status>("OldStatus")
                        .HasColumnType("status")
                        .HasColumnName("old_status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_edits");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_edits_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_edits_user_id");

                    b.ToTable("edits", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("SendDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_date_time");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_notifications_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("repository_url");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("RepositoryUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_repository_url");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("ReplyDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reply_date_time");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_replies");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_replies_author_user_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_replies_ticket_id");

                    b.ToTable("replies", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date_time");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Priority>("Priority")
                        .HasColumnType("priority")
                        .HasColumnName("priority");

                    b.Property<Status>("Status")
                        .HasColumnType("status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<TicketType>("Type")
                        .HasColumnType("ticket_type")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("ix_tickets_creator_user_id");

                    b.HasIndex("OperatorUserId")
                        .HasDatabaseName("ix_tickets_operator_user_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_tickets_platform_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AreEmailNotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("are_email_notifications_enabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<UserType>("Type")
                        .HasColumnType("user_type")
                        .HasColumnName("type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_user_notifications_notification_id");

                    b.HasIndex("ReceiverUserId", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_notifications_receiver_user_id_notification_id");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.UserPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlatformId")
                        .HasMaxLength(50)
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_platforms");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_user_platforms_platform_id");

                    b.HasIndex("UserId", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_platforms_user_id_platform_id");

                    b.ToTable("user_platforms", (string)null);
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Attachment", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Edit", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.Ticket", "Ticket")
                        .WithMany("Edits")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edits_tickets_ticket_id");

                    b.HasOne("ADAtickets.Shared.Models.User", "User")
                        .WithMany("Edits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edits_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Notification", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.Ticket", "Ticket")
                        .WithMany("Notifications")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_tickets_ticket_id");

                    b.HasOne("ADAtickets.Shared.Models.User", "User")
                        .WithMany("SentNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Reply", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.User", "AuthorUser")
                        .WithMany("Replies")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_replies_users_author_user_id");

                    b.HasOne("ADAtickets.Shared.Models.Ticket", "Ticket")
                        .WithMany("Replies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_replies_tickets_ticket_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Ticket", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.User", "CreatorUser")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_creator_user_id");

                    b.HasOne("ADAtickets.Shared.Models.User", "OperatorUser")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("OperatorUserId")
                        .HasConstraintName("fk_tickets_users_operator_user_id");

                    b.HasOne("ADAtickets.Shared.Models.Platform", "Platform")
                        .WithMany("Tickets")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_platforms_platform_id");

                    b.Navigation("CreatorUser");

                    b.Navigation("OperatorUser");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.UserNotification", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_notifications_notification_id");

                    b.HasOne("ADAtickets.Shared.Models.User", "ReceiverUser")
                        .WithMany("UserNotifications")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_users_receiver_user_id");

                    b.Navigation("Notification");

                    b.Navigation("ReceiverUser");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.UserPlatform", b =>
                {
                    b.HasOne("ADAtickets.Shared.Models.Platform", "Platform")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_platforms_platforms_platform_id");

                    b.HasOne("ADAtickets.Shared.Models.User", "User")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_platforms_users_user_id");

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Platform", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("UserPlatforms");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Edits");

                    b.Navigation("Notifications");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ADAtickets.Shared.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("Edits");

                    b.Navigation("Replies");

                    b.Navigation("SentNotifications");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
