// <auto-generated />
using System;
using ADAtickets.ApiService.Configs;
using ADAtickets.ApiService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ADAtickets.ApiService.Migrations
{
    [DbContext(typeof(ADAticketsDbContext))]
    [Migration("20250504071537_Refactor")]
    partial class Refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "priority", new[] { "high", "low", "medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "closed", "unassigned", "waiting_operator", "waiting_user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_type", new[] { "bug", "feature" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_type", new[] { "admin", "operator", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ADAtickets.ApiService.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("path");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_attachments_ticket_id");

                    b.HasIndex("Path", "TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_path_ticket_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Edit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EditDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edit_date_time");

                    b.Property<Status>("NewStatus")
                        .HasColumnType("status")
                        .HasColumnName("new_status");

                    b.Property<Status>("OldStatus")
                        .HasColumnType("status")
                        .HasColumnName("old_status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_edits");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_edits_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_edits_user_id");

                    b.ToTable("edits", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_notifications_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("repository_url");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_name");

                    b.HasIndex("RepositoryUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_repository_url");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("ReplyDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reply_date_time");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_replies");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_replies_author_user_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_replies_ticket_id");

                    b.ToTable("replies", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Priority>("Priority")
                        .HasColumnType("priority")
                        .HasColumnName("priority");

                    b.Property<Status>("Status")
                        .HasColumnType("status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<TicketType>("Type")
                        .HasColumnType("ticket_type")
                        .HasColumnName("type");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("ix_tickets_creator_user_id");

                    b.HasIndex("OperatorUserId")
                        .HasDatabaseName("ix_tickets_operator_user_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_tickets_platform_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AreEmailNotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("are_email_notifications_enabled");

                    b.Property<bool>("ArePhoneNotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("are_phone_notifications_enabled");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsEmail2FAEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email2fa_enabled");

                    b.Property<bool>("IsPhone2FAEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone2fa_enabled");

                    b.Property<string>("MicrosoftAccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("microsoft_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<UserType>("Type")
                        .HasColumnType("user_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("ix_app_users_identity_user_id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.UserNotification", b =>
                {
                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.HasKey("ReceiverUserId", "NotificationId")
                        .HasName("pk_user_notifications");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_user_notifications_notification_id");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.UserPlatform", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PlatformId")
                        .HasMaxLength(50)
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.HasKey("UserId", "PlatformId")
                        .HasName("pk_user_platforms");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_user_platforms_platform_id");

                    b.ToTable("user_platforms", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.Property<Guid>("ReceivedNotificationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_notifications_id");

                    b.Property<Guid>("RecipientsId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipients_id");

                    b.HasKey("ReceivedNotificationsId", "RecipientsId")
                        .HasName("pk_notification_user");

                    b.HasIndex("RecipientsId")
                        .HasDatabaseName("ix_notification_user_recipients_id");

                    b.ToTable("notification_user", (string)null);
                });

            modelBuilder.Entity("PlatformUser", b =>
                {
                    b.Property<Guid>("PreferredPlatformsId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_platforms_id");

                    b.Property<Guid>("UsersPreferredId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_preferred_id");

                    b.HasKey("PreferredPlatformsId", "UsersPreferredId")
                        .HasName("pk_platform_user");

                    b.HasIndex("UsersPreferredId")
                        .HasDatabaseName("ix_platform_user_users_preferred_id");

                    b.ToTable("platform_user", (string)null);
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Attachment", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Edit", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Ticket", "Ticket")
                        .WithMany("Edits")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edits_tickets_ticket_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", "User")
                        .WithMany("Edits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edits_app_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Notification", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Ticket", "Ticket")
                        .WithMany("Notifications")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_tickets_ticket_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", "User")
                        .WithMany("SentNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_app_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Reply", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.User", "AuthorUser")
                        .WithMany("Replies")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_replies_app_users_author_user_id");

                    b.HasOne("ADAtickets.ApiService.Models.Ticket", "Ticket")
                        .WithMany("Replies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_replies_tickets_ticket_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Ticket", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.User", "CreatorUser")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_app_users_creator_user_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", "OperatorUser")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("OperatorUserId")
                        .HasConstraintName("fk_tickets_app_users_operator_user_id");

                    b.HasOne("ADAtickets.ApiService.Models.Platform", "Platform")
                        .WithMany("Tickets")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_platforms_platform_id");

                    b.Navigation("CreatorUser");

                    b.Navigation("OperatorUser");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_users_users_identity_user_id");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.UserNotification", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_notifications_notification_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", "ReceiverUser")
                        .WithMany("UserNotifications")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_app_users_receiver_user_id");

                    b.Navigation("Notification");

                    b.Navigation("ReceiverUser");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.UserPlatform", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Platform", "Platform")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_platforms_platforms_platform_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", "User")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_platforms_app_users_user_id");

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Notification", null)
                        .WithMany()
                        .HasForeignKey("ReceivedNotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_notifications_received_notifications_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_app_users_recipients_id");
                });

            modelBuilder.Entity("PlatformUser", b =>
                {
                    b.HasOne("ADAtickets.ApiService.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PreferredPlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_user_platforms_preferred_platforms_id");

                    b.HasOne("ADAtickets.ApiService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersPreferredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_user_app_users_users_preferred_id");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Platform", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("UserPlatforms");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Edits");

                    b.Navigation("Notifications");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ADAtickets.ApiService.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("Edits");

                    b.Navigation("Replies");

                    b.Navigation("SentNotifications");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
