//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAtickets.Installer.Assets {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADAtickets.Installer.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API app ID:.
        /// </summary>
        public static string ApiAppIdLabel {
            get {
                return ResourceManager.GetString("ApiAppIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API authentication certificate password:.
        /// </summary>
        public static string ApiAuthCertificatePasswordLabel {
            get {
                return ResourceManager.GetString("ApiAuthCertificatePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API authentication certificate path (local):.
        /// </summary>
        public static string ApiAuthCertificatePathLabel {
            get {
                return ResourceManager.GetString("ApiAuthCertificatePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pulling API container....
        /// </summary>
        public static string ApiContainerPull {
            get {
                return ResourceManager.GetString("ApiContainerPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API version:.
        /// </summary>
        public static string ApiVersionLabel {
            get {
                return ResourceManager.GetString("ApiVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Basic auth password:.
        /// </summary>
        public static string BasicAuthPasswordLabel {
            get {
                return ResourceManager.GetString("BasicAuthPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Basic auth username:.
        /// </summary>
        public static string BasicAuthUsernameLabel {
            get {
                return ResourceManager.GetString("BasicAuthUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a username.
        /// </summary>
        public static string BasicUsernameWatermark {
            get {
                return ResourceManager.GetString("BasicUsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pulling cache container....
        /// </summary>
        public static string CacheContainerPull {
            get {
                return ResourceManager.GetString("CacheContainerPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a /path/to/certificate.pfx.
        /// </summary>
        public static string CertificatePathWatermark {
            get {
                return ResourceManager.GetString("CertificatePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cleaning temporary files....
        /// </summary>
        public static string CleaningTemp {
            get {
                return ResourceManager.GetString("CleaningTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting up containers with Compose....
        /// </summary>
        public static string ComposeStartup {
            get {
                return ResourceManager.GetString("ComposeStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pulling database container....
        /// </summary>
        public static string DbContainerPull {
            get {
                return ResourceManager.GetString("DbContainerPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database password:.
        /// </summary>
        public static string DbPasswordLabel {
            get {
                return ResourceManager.GetString("DbPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database username:.
        /// </summary>
        public static string DbUserNameLabel {
            get {
                return ResourceManager.GetString("DbUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DevOps organization name:.
        /// </summary>
        public static string DevOpsOrganizationNameLabel {
            get {
                return ResourceManager.GetString("DevOpsOrganizationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Writing the environment file....
        /// </summary>
        public static string EnvFileWriting {
            get {
                return ResourceManager.GetString("EnvFileWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while setting up:.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Example Name.
        /// </summary>
        public static string ExampleNameWatermark {
            get {
                return ResourceManager.GetString("ExampleNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External API app ID:.
        /// </summary>
        public static string ExternalApiAppIdLabel {
            get {
                return ResourceManager.GetString("ExternalApiAppIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External tenant ID:.
        /// </summary>
        public static string ExternalTenantIdLabel {
            get {
                return ResourceManager.GetString("ExternalTenantIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External web app ID:.
        /// </summary>
        public static string ExternalWebAppIdLabel {
            get {
                return ResourceManager.GetString("ExternalWebAppIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This field is mandatory..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hello!.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installing ADAtickets....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The domain is invalid..
        /// </summary>
        public static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The GUID is invalid..
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid organization name..
        /// </summary>
        public static string InvalidOrganizationName {
            get {
                return ResourceManager.GetString("InvalidOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The path is invalid..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a password.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert the following information to continue with the setup..
        /// </summary>
        public static string PleaseInsert {
            get {
                return ResourceManager.GetString("PleaseInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Before running this setup, read the instructions in the README file..
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service principal ID:.
        /// </summary>
        public static string ServicePrincipalIdLabel {
            get {
                return ResourceManager.GetString("ServicePrincipalIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setup completed successfully..
        /// </summary>
        public static string SetupCompleted {
            get {
                return ResourceManager.GetString("SetupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SSL certificate password:.
        /// </summary>
        public static string SslCertificatePasswordLabel {
            get {
                return ResourceManager.GetString("SslCertificatePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SSL certificate path (local):.
        /// </summary>
        public static string SslCertificatePathLabel {
            get {
                return ResourceManager.GetString("SslCertificatePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Still waiting for Docker startup. Did you launch it?.
        /// </summary>
        public static string StillWaitingDocker {
            get {
                return ResourceManager.GetString("StillWaitingDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant ID:.
        /// </summary>
        public static string TenantIdLabel {
            get {
                return ResourceManager.GetString("TenantIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Volume mount path (local):.
        /// </summary>
        public static string VolumePathLabel {
            get {
                return ResourceManager.GetString("VolumePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting for Docker startup....
        /// </summary>
        public static string WaitingDocker {
            get {
                return ResourceManager.GetString("WaitingDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web app ID:.
        /// </summary>
        public static string WebAppIdLabel {
            get {
                return ResourceManager.GetString("WebAppIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web app authentication certificate password:.
        /// </summary>
        public static string WebAuthCertificatePasswordLabel {
            get {
                return ResourceManager.GetString("WebAuthCertificatePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web app authentication certificate path (local):.
        /// </summary>
        public static string WebAuthCertificatePathLabel {
            get {
                return ResourceManager.GetString("WebAuthCertificatePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pulling web container....
        /// </summary>
        public static string WebContainerPull {
            get {
                return ResourceManager.GetString("WebContainerPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a App version:.
        /// </summary>
        public static string WebVersionLabel {
            get {
                return ResourceManager.GetString("WebVersionLabel", resourceCulture);
            }
        }
    }
}
