name: Tag latest commit
on:
  workflow_run:
    workflows:
    - SonarQube
    types: 
    - completed

jobs:
  tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Git
        run: |
          git config user.name "Andrea Lucchese"
          git config user.email "andrylook14@gmail.com"
      
      - name: Generate tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Push tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin ${{ env.TAG_NAME }}
